version: '3'

services:
  crawler:
    build: ./crawler
    depends_on:
      - db
    command: python main.py
    volumes:
      - ./crawler:/crawler

  db:
    image: mongo
    volumes:
      - sicav_db:/data/db
    ports:
      - "27017:27017"

  test:
    build: ./crawler
    depends_on:
      - db
    command: pytest tests/
    volumes:
      - ./crawler:/crawler

  api:
    build: ./api
    depends_on:
      - db
    volumes:
      - ./api:/api
    ports:
      - "8080:80"

volumes:
  sicav_db:
